### ISSUE TITLE
porting to mysql

### ISSUE THREAD

**Issue by ghost** [posix4e/jsoncdc#31]
Hi-

I realize this is early days, but... is it now possible to modularize this to listen to MySQL replication as well as PostgresQL? Do you think it will ever be?

(I found you from Alex's talk at Elasticsearch.)

**Comment by solidsnack** [comment]
This is not actually a listener but a formatter. (We do have some thoughts about a listener that would handle the generated JSON; but this project is just the formatter.)

A logical decoding plugin -- which is presently all the project provides -- is a loadable module that is loaded _by the Postgres server_ to format change logs for replication clients. That accounts for some of the oddities in the Makefile, like passing special compiler options for symbol resolution on Macintosh.

I suspect this is very different from how MySQL handles replication formatting. (But please do correct me if I am wrong.)

As regards support for MySQL, we'd definitely like to see a comprehensive and portable approach to CDC for relational databases. At the very least, we'll ensure that the format is appropriately extensible; and the model should allow for replay from Postgres to MySQL (or any other database, translating type names as needed). But I think a project with a very different layout would be necessary for implementing the same format for MySQL, because as I understand it, such tools simply parse MySQL's write-ahead logs instead of providing in-server callbacks.

**Comment by solidsnack** [comment]
@lance-edmodo How does the [format described in the README](https://github.com/posix4e/jsoncdc#usage) look to you, from a MySQL perspective?

**Comment by ghost** [comment]
I don't know, I'm not a MySQL expert.

**Comment by posix4e** [comment]
I'd be happy to give you information on mysql. posix4e@gmail.com
